### PR TITLE
Fix removing "default" results 

### LINKED ISSUE #56: Incompatible with Kemini?
This mod seems to stuff up the "Review Experiment" dialog for Kemini experiments.

See https://github.com/mwerle/OrbitalMaterialScience/issues/15 and https://github.com/mwerle/OrbitalMaterialScience/issues/16

Any ideas as to what the cause might be? Anything I can do to fix it on the Kemini side?

Was testing using KSP1.3.1 today.

### PR DESCRIPTION
**Pull request by mwerle**
This pull request retains existing "default" results or those already ending in asterisk (*) defined in mods.

Verified to fix #56.

### CODE REVIEW

**Comment by mwerle** [comment]
This functionality was originally broken by e1fb574

**Comment by Olympic1** [comment]
Thanks for the fix

**Comment by mwerle** [comment]
Ok, now also confirmed that this fixes both of my Kemini issues.

Thanks for the quick merge, but I hope it doesn't break other mods now? I'm not entirely sure what KSP bug this plugin is actually supposed to fix and why it's needed..

**Comment by Olympic1** [comment]
The plugin fixes the issue that it wasn't possible to display different reports each time the same experiment was rerun. You constantly got the same report over again.

**Comment by mwerle** [comment]
Hmm, ok, haven't seen that personally, but doing some reading I see that bug was only introduced "recently" (2 versions ago).

Which means my fix might break that again. I'll do some more testing.

**Comment by mwerle** [comment]
Ok, I tested using a temp sensor on the launchpad and additional results strings in CSS.

Using the fixed dll, it randomly selects from the original KSP-supplied results as well as the "default" and location-specific CSS ones.

Disabling the dll, it always returns the first location-specific result from CSS.

So basically, it seems to work as intended now.

**Pull request merged**
