### PR TITLE
Add support for StationScience

### PR DESCRIPTION
**Pull request by madsailor**
This doesn't add any new content, but it sets up support for [StationScience](http://forum.kerbalspaceprogram.com/threads/54774).

### CODE REVIEW

**Comment by Olympic1** [comment]
If a mod has its own science reports, we don't have to include it here

**Comment by madsailor** [comment]
It does have most of its own reports, but it's not complete. Particularly for the bioproducts and kuarksBioproducts experiments.

**Comment by Olympic1** [comment]
If we should add every mod that doesn't yet support the new biomes, then we will need to add a lot of mods. Not every mod wants to provide support for the new biomes, but just wants to keep it by planets.

The best way to add experiments for a mod is to add it by the mod itself.

**Comment by DuoDex** [comment]
Merged. It doesn't actually add support for 0.90 biomes, so it shouldn't bother the mod authors.

**Comment by harryyoung** [comment]
You're sure you hit the right button, DuoDex?

**Comment by madsailor** [comment]
This pull request got me thinking about what CSS really is: a stopgap measure.  For the base game I think we can be safe in assuming that Squad will eventually add their own science reports for all the biomes, it is just a mountain of content to add, so they implemented functionality first.  When they eventually do, CSS will no longer serve a compelling purpose in that arena.  
This leaves the mod scene as the long-term arena in which CSS may continue to be needed.  However, any mod can add content directly, rather than content coming by proxy through CSS.  
For this reason perhaps it would make sense to direct content directly to the 'upstream' mod first, and only if there are science reports that the upstream mod is unwilling/unable to add, to then add mod support to CSS.  Else there is just a nebulous definition of what is enough content to justify addition (ex. SCANSat vs StationScience)

My reasoning for adding StationScience was this:  

* It is the most downloaded science mod on curseforge  
* It does not have a full set of reports for each planet/experiment combination (biomes aside)  
* It allows each experiment to be performed 3 times, and there is at most 1 report for each planet/experiment combination  
* The most popular poll answer on the thread is "Expand, with an eye towards support for other science mods."  Rather than just "Add more science reports!"  
* After learning and editing the process for adding experiment and planet support on the wiki I was interested in trying it myself  

So from here, do we contact upstream to add more reports, or do we add support for the mod here?  FWIW [Sounding Rockets](http://forum.kerbalspaceprogram.com/threads/102502) also falls in the same 'some but not much' content category for science reports, and I'm pretty sure Roverdude has a few things on his agenda that take priority over adding science reports, just like Squad does. In any case I think it's worth thinking about and coming up with a policy.

**Comment by harryyoung** [comment]
I'd like to respond, however a pull request - particularry one that should already be closed - is not a good place to discuss this.

**Comment by madsailor** [comment]
"I'd like to respond, however a pull request - particularry one that should already be closed - is not a good place to discuss this."
OK. I'm not sure where the best place for discussion like this is.  If you would like to open an issue on Github, or start a dev thread on the KSP forums I'd be happy to hear every-ones thoughts...that's why I posted here.

**Pull request merged**
