### PR TITLE
Mod support

### PR DESCRIPTION
**Pull request by ImAHungryMan**
A small start on support for KSPI, StationScience, USI, DMOS.

### CODE REVIEW

**Comment by madsailor** [comment]
A few minor changes:

000_default/KSPI.cfg
line 27 should be "separate" and "compounds"

000_default/SCANsat.cfg
line 22 should be "You could do this all day!"

000_default/USI_SR.cfg 
line 24 should be "periodically"
line 46 should be "faster and farther than anyone has ever gone before."

/kerbin/default/USI_SR.cfg
line 54 should be "compartment"
line 77 should be "variety"

Push a commit with these changes and we can merge your pull request.  Nice reports.

**Comment by ImAHungryMan** [comment]
You guys are good, goddamn.

**Comment by Olympic1** [comment]
Maybe use notepad++, it has a spelling checker

**Comment by ImAHungryMan** [comment]
Will do. Thanks.

**Pull request merged**
